# Generated by Django 5.2.9 on 2025-12-24 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="evaluationmodel",
            old_name="event_id",
            new_name="event",
        ),
        migrations.AlterField(
            model_name="evaluationmodel",
            name="event",
            field=models.ForeignKey(
                blank=True,
                db_column="event_id",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="evaluations",
                to="app.eventmodel",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="evaluationmodel",
            unique_together={("event", "evaluated_user_id", "evaluator_user_id")},
        ),
        migrations.AlterField(
            model_name="evaluationanswermodel",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="evaluationmodel",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="eventmodel",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
