# Generated by Django 5.2.9 on 2025-12-24 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_alter_evaluationmodel_unique_together_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="InternHoursModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("horas", models.IntegerField()),
                ("horas_jul_oct", models.IntegerField()),
                ("horas_acumuladas", models.IntegerField()),
                ("horas_necesarias", models.IntegerField()),
                ("horas_restantes_2212", models.IntegerField()),
                ("falta_sobra", models.IntegerField()),
                ("faltaria_sobraria", models.IntegerField()),
                ("total", models.IntegerField()),
                (
                    "cumplimiento_pct",
                    models.IntegerField(
                        help_text="Porcentaje entero de cumplimiento (ej. 79 = 79%)"
                    ),
                ),
            ],
            options={
                "db_table": "intern_hours",
                "ordering": ["name"],
            },
        ),
    ]
